name: rocket_pocket
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.12
  path: ^1.8.2
  talker: ^4.7.1
  talker_flutter: ^4.7.1
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.0.0
  flutter_adaptive_scaffold: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.7.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
